USE library;
DELETE FROM author;
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Joshua", "Brown");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Javier", "Dixon");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Wanda", "Patton");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Ashley", "Patterson");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Phillip", "Chang");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Kaylee", "Lopez");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Cathy", "Martin");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Nicholas", "Adams");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Jamie", "Rhodes");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Jasmine", "Hall");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Amanda", "James");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Ryan", "Johnson");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Teresa", "Pearson");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Christina", "Bennett");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Kim", "Velasquez");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Christopher", "Woodard");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("John", "Lam");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Christopher", "Alexander");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Nathaniel", "Gonzales");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Adam", "Harris");
DELETE FROM book;
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-17-998052-1", "Human improve head data choice over.", "1509", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-923291-55-5", "Herself out behavior.", "1272", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-451-42074-8", "Piece store south.", "2806", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-670-97795-0", "Own among opportunity ball.", "2480", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-68958-364-9", "Than such fly behavior air bed.", "2718", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-592-48761-X", "Away history prove range.", "2850", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-441-42560-7", "North stock drug bank cell.", "4212", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-404-34394-5", "Pretty here both.", "304", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-246-64225-5", "Join deal hundred store seven staff.", "256", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-605-59252-7", "Member sign theory I war laugh.", "4948", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-519-63803-4", "Know central include.", "3114", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7815-8045-5", "Wife contain however month.", "3212", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-347-12341-5", "Financial model feeling run need carry pull.", "779", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-920048-40-4", "Themselves family buy.", "234", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-232-75205-3", "Allow seek billion behavior identify produce.", "1142", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-82186-835-8", "Reveal concern tell available task break.", "2212", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-14-032075-X", "Authority third difficult at same.", "2458", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-81353-179-X", "American Democrat key.", "4171", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7941-9432-X", "Media clearly seven design.", "3275", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-82710-369-8", "Evening no new.", "426", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4748-7868-7", "Common law cover note ago record.", "2214", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-63486-680-0", "Between provide hundred career government.", "4599", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-270-50341-3", "Long close teach actually different.", "3624", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-208-12019-0", "Set animal give body once hard.", "3483", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-87185-677-8", "Tax day right instead war suggest.", "3125", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7239-9566-4", "Act national exactly.", "3782", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-81039-525-9", "Maybe course forward today.", "2054", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-5250-5297-7", "Worry so management reveal fear away.", "4832", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-177-84423-0", "Window sometimes vote well.", "4600", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-646-96925-0", "Discuss science group.", "2412", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-76274-521-6", "Weight while small have follow people.", "2476", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-9894460-1-8", "Skin today because room executive.", "4110", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-164-82661-1", "Similar kitchen bar bag.", "307", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4075-9046-4", "Material discover social any.", "2135", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-86633-891-9", "Mrs similar place.", "1137", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-395-52744-9", "Lot service choice trade.", "695", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-341-97868-X", "Official television key manage specific officer.", "4660", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-563-08289-5", "Seat customer ready.", "4322", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-11-491851-1", "Actually Congress follow.", "480", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4959-2553-6", "Likely safe approach wait six.", "1521", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-56802-677-3", "Reason sound need understand enjoy.", "4426", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-17-300580-2", "Article nature Congress.", "1070", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-931085-47-0", "Natural affect per measure available player.", "3223", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-382-39024-5", "Memory put American.", "2893", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4915-4143-1", "Go fight long.", "2383", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-335-92199-X", "Exactly inside responsibility.", "1374", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-335-16233-X", "Step media some American loss.", "1943", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-456-02901-X", "Realize reach doctor movie moment.", "3333", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7064-0017-8", "Write win idea weight although discover least.", "2541", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-9912191-3-9", "Middle military drug threat police.", "3542", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4444-9721-9", "Trade require might rule TV per.", "3767", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-163-04286-2", "Choose entire relationship state southern.", "4862", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-673-59815-2", "There catch hot a case.", "4157", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-272-45159-3", "Your today southern really feel.", "3687", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-9756-0606-X", "According writer thus gas.", "3409", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-03-018467-4", "Gun total voice.", "2101", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-374-11257-6", "True attack help me.", "4625", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-02-839826-2", "Skin good but defense last.", "2566", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-234-59972-4", "Range recently according benefit town.", "1972", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-483-04464-4", "Relate garden hear.", "137", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-929653-76-9", "Approach three democratic indeed all always.", "1101", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-548-41183-2", "General own range art conference.", "693", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8126-9515-1", "Where together whole alone official throughout.", "4423", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-5100-9933-6", "Sing style cause up.", "635", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-173-07453-8", "Two forward yet environment upon technology.", "2174", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-87613-132-1", "Thing save marriage wait score thought.", "4285", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-08-279091-5", "Material before travel.", "282", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-234-03085-2", "Attack development his.", "2129", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-458-24550-X", "Bag money article.", "2136", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-227-67462-7", "Pm participant mission fund catch community.", "717", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-14-976554-1", "Trouble road new.", "3249", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-113-77290-5", "Itself exist since city friend.", "3655", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-204-36738-7", "Test could between.", "2207", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-263-49544-2", "Similar us poor.", "4203", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-58695-236-6", "Term weight shake want.", "3573", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-264-70713-4", "Fact even thought training customer.", "449", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-322-50109-2", "Find next small.", "4857", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-55800-577-3", "Religious large edge production.", "4856", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-383-33065-4", "Exactly why machine beautiful.", "1254", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-264-62188-3", "Less shake important son.", "1614", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-386-55039-6", "Look exist society way view.", "3160", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-402-55904-5", "Parent everyone yet campaign hour human.", "1360", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-172-18230-2", "Bar part world.", "993", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-9837-0081-9", "Others risk decision.", "828", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-86707-409-4", "Popular consumer understand behind either number.", "1299", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-226-68764-3", "Fast head seem no.", "2588", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-220-39900-0", "Hot million record parent success life.", "3996", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7611-9702-8", "Television election mention.", "4970", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-04-817014-3", "Create discover owner.", "3646", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-991691-38-6", "Lot but let two chair decade.", "4812", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7658-3452-9", "Interview though senior nice bring.", "4769", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-5485-1078-5", "Sign summer kitchen knowledge religious.", "1005", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-520-81968-3", "Last occur onto.", "2216", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-82867-944-5", "Situation risk participant bed ask.", "4211", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-400-79121-8", "Yes put task if mouth avoid third.", "1505", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-86183-587-6", "Clearly of business.", "1321", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-554-52490-2", "Heart easy southern increase all.", "552", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-84302-828-X", "We must serious allow.", "1684", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-483-35320-5", "Task with wait former.", "1064", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7804-3097-2", "Hotel word news.", "611", "German");
DELETE FROM book_author;
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("1", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("1", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("2", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("2", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("2", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("2", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("5", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("5", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("5", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("5", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("10", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("10", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("10", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("10", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("11", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("13", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("14", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("14", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("14", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("17", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("17", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("17", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("18", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("18", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("18", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("18", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("19", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("19", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("19", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("19", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("20", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("20", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("21", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("21", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("21", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("25", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("25", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("26", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("28", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("30", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("31", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("31", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("31", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("31", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("32", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("32", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("36", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("37", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("38", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("40", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("42", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("43", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("43", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("43", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("44", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("46", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("48", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("50", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("50", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("51", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("51", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("51", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("53", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("53", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("55", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("55", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("56", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("56", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("56", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("57", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("57", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("57", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("57", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("58", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("58", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("58", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("60", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("60", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("63", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("63", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("63", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("64", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("65", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("65", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("65", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("66", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("66", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("67", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("67", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("67", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("69", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("70", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("70", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("72", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("74", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("75", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("75", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("75", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("77", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("77", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("77", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("80", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("81", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("81", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("82", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("85", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("85", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("85", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("86", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("86", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("86", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("87", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("90", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("90", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("90", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("90", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("92", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("92", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("97", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("97", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("97", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("98", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("98", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "16");
DELETE FROM category;
INSERT INTO category (category_name)        VALUES ("Fiction");
INSERT INTO category (category_name)        VALUES ("Nonfiction");
INSERT INTO category (category_name)        VALUES ("Mystery");
INSERT INTO category (category_name)        VALUES ("Thriller");
INSERT INTO category (category_name)        VALUES ("Romance");
INSERT INTO category (category_name)        VALUES ("Science Fiction");
INSERT INTO category (category_name)        VALUES ("Fantasy");
INSERT INTO category (category_name)        VALUES ("Horror");
INSERT INTO category (category_name)        VALUES ("Biography");
INSERT INTO category (category_name)        VALUES ("History");
INSERT INTO category (category_name)        VALUES ("Self-help");
INSERT INTO category (category_name)        VALUES ("Poetry");
INSERT INTO category (category_name)        VALUES ("Comedy");
INSERT INTO category (category_name)        VALUES ("Drama");
INSERT INTO category (category_name)        VALUES ("Action and Adventure");
INSERT INTO category (category_name)        VALUES ("Young Adult");
INSERT INTO category (category_name)        VALUES ("Children's");
INSERT INTO category (category_name)        VALUES ("Science");
INSERT INTO category (category_name)        VALUES ("Art");
INSERT INTO category (category_name)        VALUES ("Cooking");
DELETE FROM book_category;
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("11", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("11", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("37", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("37", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("37", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("38", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("38", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("38", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("41", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("41", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("41", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("41", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("42", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("42", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("43", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("43", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("43", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("46", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("46", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("47", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("47", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("47", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("48", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("48", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("49", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("49", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("49", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("49", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("57", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("57", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("57", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("59", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("59", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("61", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("61", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("65", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("65", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("66", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("66", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("66", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("67", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("67", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("67", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("69", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("69", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("69", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("70", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("70", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("73", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("73", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("73", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("77", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("77", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("84", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("84", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("91", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("91", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("94", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("94", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("95", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("95", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("97", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("97", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("97", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("99", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("99", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("100", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("100", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("100", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("100", "20");
