USE library;

DELETE FROM author;

USE library;
DELETE FROM author;
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Thomas", "Reyes");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Steven", "Kelly");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Rick", "Miller");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Joshua", "Garner");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Robert", "Thompson");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Brianna", "Torres");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Paige", "Jackson");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Troy", "Garza");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Stacey", "Kennedy");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Christopher", "Perry");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Ryan", "Miles");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Mary", "Hoffman");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Jacob", "Collins");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Jason", "Jennings");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Ashley", "Obrien");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Timothy", "Lynn");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Jonathan", "Esparza");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Eric", "Smith");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Kenneth", "Harmon");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("John", "Jimenez");
DELETE FROM book;
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-06-428155-8", "Level federal paper exactly exactly matter.", "3965", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-423-91274-7", "Course together sing these foreign.", "4172", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-09-544684-2", "Thought member conference name administration.", "2804", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4668-9300-1", "Improve artist there consider quickly affect.", "4678", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-84596-812-3", "Person age bit job situation environment.", "3497", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-329-81743-4", "Media government discover house modern.", "4094", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-9862-0515-0", "So action environmental drive.", "1455", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-361-37360-1", "Drug them town.", "2572", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-353-98637-3", "Ball apply woman all cut quickly.", "1683", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-200-94937-4", "Human body girl cell left.", "974", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-118-07378-9", "Machine hair five wall usually.", "4792", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-55978-524-1", "Interview certain it far.", "693", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-467-74335-5", "Wide grow situation deal.", "2160", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-65647-909-5", "Serious cover area.", "3767", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7566-4971-4", "Especially small cell minute still.", "443", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-419-33890-X", "Effort tree player.", "1208", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-588-74424-7", "Use low benefit future.", "2215", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-889178-09-8", "Follow else doctor without explain current.", "4697", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-152-66302-X", "Statement their interview treat Mrs.", "2611", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-89996-143-6", "Father likely certainly.", "4994", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-14-364003-8", "Already force item care.", "136", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-17-574426-2", "Sea front little.", "272", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-05-862522-4", "History seem a security mean.", "1638", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-69948-829-0", "Single support woman represent idea.", "2722", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-303-14798-9", "Nation last main act growth.", "1433", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-587-34422-9", "According still chair long create suddenly.", "186", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8084-2191-3", "Customer game whole.", "1885", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7234-9709-5", "Way range billion approach ask.", "1966", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-922642-99-0", "Kid enough board join agreement.", "2186", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-82948-635-7", "Send interest find son.", "1758", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-68964-740-X", "Summer war current open the current.", "2578", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-537-75098-3", "Bill mother artist industry skill real.", "4109", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-09-200449-1", "North again husband involve require agreement.", "4600", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-172-62373-2", "I store list or despite.", "535", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-65396-040-X", "Near type day skill half.", "3790", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-64191-125-5", "Wear seven always.", "2398", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-905080-24-6", "International my foreign.", "2962", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-237-99719-3", "Although once maintain sort.", "1755", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7057-9372-9", "Class fire bad add special west.", "333", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-10-926030-9", "Present unit election risk.", "2748", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-01-794624-8", "I thousand citizen lot continue local.", "2130", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-05-087221-5", "At account single billion local discussion knowledge.", "603", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-04-588882-6", "Talk seven water civil drug final.", "2251", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-87233-886-X", "Increase attention direction debate property.", "554", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7297-9632-9", "Take reality even event.", "4604", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-01-232557-0", "Reality across stuff policy state weight.", "3213", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-909167-63-0", "Themselves well today.", "156", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7788-1512-9", "Those cultural may day.", "2721", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-224-27679-5", "Manager measure remain station.", "56", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-906471-61-3", "Accept impact relate cell actually.", "2491", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8067-3891-X", "Central word despite.", "1504", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-131-97505-7", "Foot medical work soldier camera produce.", "1473", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-61422-938-4", "Choose source radio listen bill number.", "1354", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-262-68403-X", "Protect prove hard project final hand.", "3539", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-57883-595-X", "Their perform marriage yard catch away.", "4370", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-259-51528-0", "Red animal old last.", "2679", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7797-5139-6", "Spring create yourself popular.", "2238", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-442-04509-3", "Everyone within college.", "3458", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-56372-682-3", "Then key yourself.", "3556", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-85681-199-9", "Positive spring role test soldier scene.", "3053", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-13-616980-5", "Senior product financial camera.", "1634", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-661-81045-3", "Stand job thus able prevent.", "1403", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-421-94136-7", "Cause particularly agent seem.", "2788", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-239-68659-4", "Situation develop perform message.", "4999", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-56006-025-5", "Law cold church fact situation.", "2592", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7381-6382-1", "Seek lose if cost she life.", "2217", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-00-197946-9", "Sing thing physical any because.", "2140", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-85535-753-4", "Build discuss president.", "1459", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7071-7355-8", "Station take yard these public.", "3331", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-9743-7919-1", "Note age ahead father film boy.", "3430", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-9793-6260-2", "Research chance research same.", "921", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-667-75909-3", "Choose fight everyone turn.", "1360", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-61194-533-X", "Value appear inside.", "3439", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-16-796543-3", "Policy statement would movie sound east.", "612", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-5472-4151-9", "Man single painting author current.", "312", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-06-690441-3", "Box market put onto think for.", "1943", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-608-09553-2", "Right person speech yourself.", "2118", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7408-5936-6", "Necessary each responsibility state.", "944", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-02-955981-3", "Produce movie think art public yes.", "1947", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-140-89026-3", "Green life according interesting.", "2027", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-136-23060-2", "Issue tonight the any network.", "4357", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-72362-149-8", "Campaign think guess woman night word.", "71", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-260-41766-1", "Husband six kitchen list federal shoulder.", "290", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8372-8405-8", "Beyond itself board.", "1078", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-516-74897-1", "Still staff kitchen.", "4796", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-277-78744-1", "Family hard after.", "3899", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-239-02450-8", "Quality billion administration certainly travel soldier.", "1875", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-203-57123-1", "Business art difficult dinner last discuss.", "2130", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-546-97081-8", "Art idea begin.", "3904", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-72552-703-0", "Whole space front citizen year item.", "1536", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-193-60883-X", "Always respond or Democrat life fine.", "3876", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4409-4792-9", "Will television side during anyone choice.", "3669", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-266-90391-7", "Pass phone few military somebody evening.", "191", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-994045-67-1", "Low relationship environment.", "3367", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-506-61551-0", "Just mean onto performance.", "4720", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4781-6290-2", "Big stand participant myself.", "3628", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-204-94922-0", "Fact item reveal newspaper nor wear.", "4207", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-592-65893-7", "Television southern increase participant example.", "4737", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-413-74592-9", "Eat plan debate mean best marriage.", "3002", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-677-17691-0", "Available join scene country here politics.", "538", "Frech");
