USE library;

INSERT INTO author (author_first_name,author_last_name)        VALUES ("Kara", "Thomas");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Charlene", "Johnson");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Michael", "Holmes");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Teresa", "Roberts");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Barbara", "Hernandez");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Alyssa", "Rivera");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Kent", "Weaver");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Debra", "Hayes");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Melissa", "Brown");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Michael", "Burns");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Anthony", "Phillips");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Renee", "Campbell");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Alan", "Pena");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Brian", "Wright");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Michael", "Edwards");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Michael", "Vaughn");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Barry", "Smith");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Brenda", "Lang");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Brian", "Cervantes");
INSERT INTO author (author_first_name,author_last_name)        VALUES ("Christian", "Conley");

INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-146-47780-5", "To thing team.", "2725", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7582-1421-9", "Second nature arrive item sort.", "671", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-75231-896-X", "Organization rich manager plant might gas.", "2915", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-301-51401-2", "Magazine recently of lawyer fish.", "2990", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-79109-871-1", "Use wait apply keep dog.", "4329", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-699-09125-X", "Fine both arrive method.", "4763", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-611-41617-4", "Would suffer deep age coach school.", "2957", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-04-615399-3", "General thousand call once.", "2843", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-61706-509-9", "Property Mrs low edge drive.", "4202", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-06-557526-1", "Various course on.", "2643", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-229-44130-1", "Who TV area true.", "3531", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-696-17529-0", "Pressure effort stand play American attack.", "4181", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-59858-902-4", "Age success plan lead firm.", "4824", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-01-227385-7", "Sort would risk.", "2994", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-274-73087-2", "Possible worry really method return.", "3891", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-886121-04-4", "Kid different wait blood prepare wonder.", "2450", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-699-05673-X", "Hour market girl financial long stand.", "3578", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-00-640886-9", "Pull explain big might indicate early.", "2222", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-871718-38-4", "Strategy visit picture age.", "3839", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8376-4660-X", "Risk thousand read.", "2684", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-233-29713-9", "Without attack end.", "3498", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-86051-906-7", "From something thousand.", "1729", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-206-61085-9", "Marriage food no.", "1439", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-288-36147-5", "Case son material manager should.", "3719", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-5263-7780-2", "Use act prepare western.", "1740", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8194-6130-X", "Recent remember outside.", "1633", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-900387-49-2", "Catch now head.", "888", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-353-43638-0", "Human important price.", "2310", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-663-95452-5", "Seek big reach have light especially.", "142", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-15-956038-1", "Effect outside more indicate.", "4485", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-01-519838-3", "Instead during man trip degree unit.", "1344", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-380-14960-6", "Social international over.", "1349", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-632-84071-4", "Significant at month drug foot tend.", "1754", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-05-408869-1", "List easy certain represent fine.", "285", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-375-52358-9", "Effort recently indeed civil.", "465", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-590-05133-4", "Whole hour join clear ability finally.", "1408", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-944973-86-9", "If need where.", "1195", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-246-97400-1", "Impact area give end.", "162", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-997441-09-8", "Anything hot stay.", "1437", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-458-54031-5", "Boy information road why.", "1258", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7276-5020-3", "Yeah ever trial.", "4169", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-880393-46-8", "Billion anything keep read.", "475", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-5072-2766-3", "Art hair rich military.", "4079", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-594-81655-6", "Series win attention necessary hard.", "519", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-08-543362-5", "Growth tough idea let able watch once.", "2694", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-235-55981-5", "Party send method five whom.", "2479", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-913415-96-1", "Carry option rather.", "2673", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-9824355-1-7", "This begin wear reveal.", "3704", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-279-11711-6", "Thus camera rich party among military dream.", "288", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7469-6541-9", "Report somebody along door administration check.", "2565", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-357-61959-5", "Wall ever financial I performance tough.", "3233", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-240-70580-7", "Major can possible push speech.", "4648", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8360-3700-6", "Book purpose indicate attention pressure.", "2413", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-16-213465-7", "Grow assume lot.", "2755", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-436-65145-9", "While remember our enough.", "990", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-56143-685-2", "Worry matter choice body plant.", "4520", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-295-27158-3", "Impact dog claim drug operation huge.", "4905", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-71383-307-7", "Within win suggest.", "1423", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7814-7947-9", "Assume write hold.", "3795", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-248-43808-5", "Act knowledge military ok nice success.", "2368", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8442-2939-3", "Day realize bag friend response.", "2904", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4750-4825-4", "Like production more particular boy top.", "4178", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-947514-41-4", "Must family value if pick.", "1665", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-02-823933-5", "Skin you form next film later.", "2357", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-450-60087-4", "Word some back others.", "4330", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-296-00145-7", "Stuff pressure piece style let.", "938", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-12-707195-4", "Move simply book early section fill.", "1656", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-445-94916-3", "Through ready suffer.", "1275", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8076-5305-5", "Really such owner such adult.", "1374", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-9517501-9-4", "Soon own my education.", "4220", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-446-57501-1", "Tonight cut another see media.", "1572", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-940125-54-4", "Forward speech commercial.", "4170", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-82242-393-7", "Kind participant form professor admit true.", "1072", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-312-91597-8", "Guy society choose.", "4319", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-669-56813-9", "Wonder toward oil purpose always toward.", "1316", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-69606-635-2", "Ahead research artist because cover.", "1242", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-317-15555-5", "Entire tough decision oil side full.", "3229", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4582-2006-0", "Address eye already suggest institution view.", "175", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-85338-253-0", "Choose moment doctor act.", "837", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7222-3456-2", "Game figure give total.", "4554", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-8046-8513-4", "Special around public pull.", "4848", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-01-440010-4", "Seven Congress away marriage also professional.", "2757", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-66891-036-5", "Management heavy goal together left guy.", "4568", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-87283-919-2", "Effect city figure.", "4081", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-352-70126-9", "Left region industry turn.", "1180", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-19-962616-2", "Front stuff wrong heavy project.", "1148", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-184-11992-9", "Short president right stage air poor.", "443", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-129-76013-8", "Represent become clear.", "2555", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-7905-1828-7", "While what different.", "908", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-429-61855-7", "Stop later much kind discuss.", "4718", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4341-4272-8", "Per show nothing Republican.", "991", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-04-575694-5", "Sound staff product professor.", "2079", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-4368-5504-7", "Executive production let foreign source though.", "697", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-14-413841-7", "Give wrong already inside.", "2166", "English");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-9935607-1-7", "Understand two side head.", "2066", "Frech");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-10-320442-3", "Indicate total cold yard imagine good.", "2120", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-503-66300-X", "Final station street assume hit.", "1311", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("1-202-71237-1", "When goal air phone order.", "2402", "Greek");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-2280-7283-2", "Close million know suffer lay.", "3833", "German");
INSERT INTO book (book_ISBN,book_title,book_page_no,book_language)        VALUES ("0-11-804389-7", "Else interview a cell already reality.", "1600", "Frech");

INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("1", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("2", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("3", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("4", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("5", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("6", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("7", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("8", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("9", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("10", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("10", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("11", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("11", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("11", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("11", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("11", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("12", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("13", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("13", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("13", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("14", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("15", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("16", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("17", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("17", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("18", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("19", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("19", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("20", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("20", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("20", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("21", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("21", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("22", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("23", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("24", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("25", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("25", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("25", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("25", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("26", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("26", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("26", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("26", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("27", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("28", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("28", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("28", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("28", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("28", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("29", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("30", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("30", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("30", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("30", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("30", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("31", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("31", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("32", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("32", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("33", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("34", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("35", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("36", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("36", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("37", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("38", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("38", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("38", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("38", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("38", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("39", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("40", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("40", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("40", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("40", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("40", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("41", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("42", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("42", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("42", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("43", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("43", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("43", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("44", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("44", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("44", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("44", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("44", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("45", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("46", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("46", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("47", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("48", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("49", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("50", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("51", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("52", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("53", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("53", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("53", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("53", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("54", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("55", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("56", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("56", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("57", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("58", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("58", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("59", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("60", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("60", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("60", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("60", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("61", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("62", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("63", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("64", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("64", "14");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("65", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("65", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("66", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("66", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("66", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("66", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("67", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("68", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("69", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("70", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("70", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("71", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("72", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("72", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("72", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("72", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("72", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("73", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("74", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("74", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("75", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("76", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("77", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("77", "12");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("78", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("79", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("80", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("80", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("80", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("80", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("81", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("82", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("82", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("82", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("82", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("83", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("84", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("85", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("86", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("87", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("87", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("88", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("89", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("90", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "15");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "9");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("91", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("92", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("92", "11");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "8");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("93", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "1");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "20");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("94", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "6");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("95", "7");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "5");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "16");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("96", "4");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("97", "2");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("97", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("98", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("98", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("98", "10");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "19");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "3");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("99", "18");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "17");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "13");
INSERT INTO book_author (book_book_id,author_author_id)            VALUES ("100", "6");

INSERT INTO category (category_name)        VALUES ("Fiction");
INSERT INTO category (category_name)        VALUES ("Nonfiction");
INSERT INTO category (category_name)        VALUES ("Mystery");
INSERT INTO category (category_name)        VALUES ("Thriller");
INSERT INTO category (category_name)        VALUES ("Romance");
INSERT INTO category (category_name)        VALUES ("Science Fiction");
INSERT INTO category (category_name)        VALUES ("Fantasy");
INSERT INTO category (category_name)        VALUES ("Horror");
INSERT INTO category (category_name)        VALUES ("Biography");
INSERT INTO category (category_name)        VALUES ("History");
INSERT INTO category (category_name)        VALUES ("Self-help");
INSERT INTO category (category_name)        VALUES ("Poetry");
INSERT INTO category (category_name)        VALUES ("Comedy");
INSERT INTO category (category_name)        VALUES ("Drama");
INSERT INTO category (category_name)        VALUES ("Action and Adventure");
INSERT INTO category (category_name)        VALUES ("Young Adult");
INSERT INTO category (category_name)        VALUES ("Children's");
INSERT INTO category (category_name)        VALUES ("Science");
INSERT INTO category (category_name)        VALUES ("Art");
INSERT INTO category (category_name)        VALUES ("Cooking");

INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("1", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("2", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("3", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("4", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("5", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("6", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("7", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("8", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("9", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("10", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("11", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("11", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("12", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("13", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("14", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("15", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("16", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("17", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("18", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("19", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("20", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("21", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("22", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("23", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("24", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("25", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("26", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("27", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("28", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("29", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("30", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("31", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("32", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("33", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("34", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("35", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("36", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("37", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("37", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("37", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("38", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("38", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("39", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("40", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("41", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("41", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("42", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("42", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("43", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("43", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("44", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("45", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("46", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("46", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("47", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("47", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("48", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("48", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("49", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("49", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("50", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("51", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("52", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("53", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("54", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("55", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("56", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("57", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("57", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("58", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("59", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("59", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("59", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("60", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("61", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("61", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("61", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("62", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("63", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("64", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("65", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("65", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("65", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("66", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("66", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("66", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("67", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("67", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("67", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("68", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("69", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("69", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("69", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("70", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("70", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("71", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("72", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("73", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("73", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("74", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("75", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("76", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("77", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("77", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("78", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("79", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("80", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("81", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("82", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("83", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("84", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("84", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("84", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("85", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("86", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("87", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("88", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("89", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("90", "2");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("91", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("91", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("91", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "10");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("92", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "12");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "1");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("93", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("94", "9");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("94", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("95", "8");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("95", "11");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("95", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "20");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "16");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "4");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "14");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "13");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("96", "18");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("97", "15");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("97", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "19");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "17");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("98", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("99", "6");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("99", "5");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("99", "3");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("100", "7");
INSERT INTO book_category (book_book_id,category_category_id)            VALUES ("100", "17");

INSERT INTO library_user_role (role_name,role_description)        VALUES ("Central Admin", "Has Controll of the database and all possible permissions");
INSERT INTO library_user_role (role_name,role_description)        VALUES ("School Admin", "Is responsible at a school level for managing the users, books, reservations");
INSERT INTO library_user_role (role_name,role_description)        VALUES ("Teacher", "Can borrow/reserve up to one book per week and edit personal info");
INSERT INTO library_user_role (role_name,role_description)        VALUES ("Student", "Can borrow/reserve up to two books per week");

INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id)            VALUES ("Mr.", "Entire.", "Erin", "Nelson", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id)            VALUES ("Receive.", "Fear.", "Amber", "James", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id)            VALUES ("Family.", "Seat.", "Annette", "Hoffman", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id)            VALUES ("School.", "Time.", "Philip", "Cook", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id)            VALUES ("Among.", "Southern.", "Daniel", "Mann", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id)            VALUES ("Agent.", "We.", "Kathleen", "Becker", "2");

INSERT INTO school (school_name,school_principal_name,library_admin_user_id,school_mail_address,city,school_phone_number,school_email)        VALUES ("Mcmahon, Riddle and Wagner", "Timothy Charles", "2",             "jcampbell@example.org", "North Nicholas", "2479997072", "kylegray@example.net");
UPDATE library_user SET school_id = 1 WHERE user_id = 2;
INSERT INTO school (school_name,school_principal_name,library_admin_user_id,school_mail_address,city,school_phone_number,school_email)        VALUES ("Byrd-Clark", "Donald Smith", "3",             "tylerromero@example.org", "South Timothy", "2744461667", "melissasmith@example.com");
UPDATE library_user SET school_id = 2 WHERE user_id = 3;
INSERT INTO school (school_name,school_principal_name,library_admin_user_id,school_mail_address,city,school_phone_number,school_email)        VALUES ("Wang-Schmidt", "Mrs. Amanda Patel", "4",             "irwinronald@example.com", "Port Juliefort", "2644467000", "jason37@example.org");
UPDATE library_user SET school_id = 3 WHERE user_id = 4;
INSERT INTO school (school_name,school_principal_name,library_admin_user_id,school_mail_address,city,school_phone_number,school_email)        VALUES ("Woodward, Hill and Atkins", "Erika Fox", "5",             "weissandrew@example.com", "Rosalesfurt", "2647061458", "michael60@example.com");
UPDATE library_user SET school_id = 4 WHERE user_id = 5;
INSERT INTO school (school_name,school_principal_name,library_admin_user_id,school_mail_address,city,school_phone_number,school_email)        VALUES ("Fox and Sons", "Jennifer Thompson", "6",             "dhenderson@example.net", "South Chadstad", "2197494383", "vsoto@example.net");
UPDATE library_user SET school_id = 5 WHERE user_id = 6;

INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Democratic.", "Speak.", "Robin", "Schultz", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Require.", "Nation.", "Norma", "Carey", "4", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("School.", "Image.", "Timothy", "Bennett", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Question.", "Else.", "Rebecca", "Ball", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Us.", "Argue.", "Darryl", "Huff", "4", "5");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("List.", "Resource.", "Antonio", "Reese", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Name.", "Sit.", "Bailey", "Cunningham", "4", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("More.", "Never.", "Kimberly", "Garcia", "4", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Decide.", "Write.", "John", "Welch", "4", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Serve.", "Particularly.", "Thomas", "Nelson", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Carry.", "Guess.", "Alisha", "Bradley", "4", "4");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Box.", "Security.", "Gregory", "Morgan", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Tree.", "Room.", "Madison", "Stephens", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Level.", "Increase.", "Christopher", "Mccormick", "4", "4");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Single.", "Report.", "David", "Carlson", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Order.", "Walk.", "Randall", "Salazar", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Nation.", "Change.", "Amy", "Long", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Professor.", "Including.", "Paige", "Rogers", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Event.", "Her.", "Crystal", "Smith", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Become.", "Mean.", "John", "Ferguson", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("See.", "Institution.", "Caleb", "Reynolds", "4", "2");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Feel.", "Foot.", "Fred", "Brown", "4", "5");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Yes.", "Seem.", "Timothy", "Cook", "4", "4");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Quickly.", "Member.", "Christine", "Hanson", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Design.", "Community.", "Brandon", "Smith", "4", "3");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Shoulder.", "Money.", "Michael", "Lewis", "4", "5");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Yeah.", "Enjoy.", "Sydney", "Simmons", "4", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Floor.", "Other.", "Melissa", "Anderson", "4", "4");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Peace.", "Realize.", "Benjamin", "Stevenson", "4", "1");
INSERT INTO library_user (username,user_password,user_first_name,user_last_name,role_id,school_id)        VALUES ("Often.", "Before.", "Shannon", "Knight", "4", "4");

INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Need.", "1");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Knowledge.", "2");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Goal.", "3");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Wall.", "4");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Hundred.", "5");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Over.", "6");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Different.", "7");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Idea.", "8");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Follow.", "9");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Law.", "10");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Understand.", "11");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Bad.", "12");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Light.", "13");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Better.", "14");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Sport.", "15");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("The.", "16");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Election.", "17");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Moment.", "18");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Road.", "19");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Foot.", "20");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Town.", "21");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Anything.", "22");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Strategy.", "23");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Production.", "24");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Share.", "25");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Movie.", "26");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Civil.", "27");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Fish.", "28");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Kind.", "29");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Fast.", "30");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Would.", "31");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Machine.", "32");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("While.", "33");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Relationship.", "34");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Describe.", "35");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Every.", "36");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Job.", "37");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Per.", "38");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Popular.", "39");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Look.", "40");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Friend.", "41");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Able.", "42");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Chair.", "43");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Story.", "44");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Room.", "45");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Who.", "46");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Point.", "47");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Over.", "48");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Professor.", "49");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Watch.", "50");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("None.", "51");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("But.", "52");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Ball.", "53");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Avoid.", "54");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Since.", "55");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Show.", "56");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Such.", "57");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Two.", "58");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Page.", "59");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Serious.", "60");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Itself.", "61");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Check.", "62");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Price.", "63");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Work.", "64");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Plan.", "65");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Go.", "66");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Enter.", "67");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Grow.", "68");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Want.", "69");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Final.", "70");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Bag.", "71");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Bag.", "72");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Seek.", "73");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Rise.", "74");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("College.", "75");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Live.", "76");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Table.", "77");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Trial.", "78");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Theory.", "79");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Effect.", "80");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("More.", "81");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Company.", "82");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Final.", "83");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Guess.", "84");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Whatever.", "85");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Think.", "86");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Old.", "87");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Ago.", "88");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Church.", "89");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Stand.", "90");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Memory.", "91");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Dream.", "92");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Suggest.", "93");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Huge.", "94");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Brother.", "95");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Half.", "96");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Necessary.", "97");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Sign.", "98");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("How.", "99");
INSERT INTO publisher (publisher_name,book_book_id)        VALUES ("Hospital.", "100");
